name: Docker Image CI -  X86_64/AARCH64 for Alpine Linux to continuous tags

on:
  push:
    branches: [ "main" ]
    tags:
      - 'continuous'
  pull_request:
    branches: [ "main" ]
  # run it manually
  workflow_dispatch:    
  schedule:
    - cron: "33 5 * * *"  
    - cron: "27 17 * * *" 

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag builder .

    - name: build static program with alpine linux docker 
      run: |
        docker run --cidfile=builder.cid builder true
        docker cp "$(cat builder.cid):work/artifact/." .
        
    - name: Upload binaries to release - guetzli
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./guetzlimm.tar.xz
        asset_name: guetzlimm-${{ runner.os }}-${{ runner.arch }}.tar.xz
        tag: refs/tags/continuous
        overwrite: true
        body: "Fully static guetzli/zopfli/mozjpeg/libwebp binary using alpine linux docker containers."       

    - name: Upload binaries to release - zopfli
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./zopflimm.tar.xz
        asset_name: zopflimm-${{ runner.os }}-${{ runner.arch }}.tar.xz
        tag: refs/tags/continuous
        overwrite: true
        body: "Fully static guetzli/zopfli/mozjpeg/libwebp binary using alpine linux docker containers." 

    - name: Upload binaries to release - mozjpeg
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./mozjpegmm.tar.xz
        asset_name: mozjpegmm-${{ runner.os }}-${{ runner.arch }}.tar.xz
        tag: refs/tags/continuous
        overwrite: true
        body: "Fully static guetzli/zopfli/mozjpeg/libwebp binary using alpine linux docker containers."         

    - name: Upload binaries to release - libwebp
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./libwebpmm.tar.xz
        asset_name: libwebpmm-${{ runner.os }}-${{ runner.arch }}.tar.xz
        tag: refs/tags/continuous
        overwrite: true
        body: "Fully static guetzli/zopfli/mozjpeg/libwebp binary using alpine linux docker containers." 
